### ISSUE TITLE
YANG model importing unused model

### ISSUE THREAD

**Issue by alexandrustancu** [openBackhaul/ltpAugment#1]
The YANG model imports another model which is unused:

`ltp-augment-1-0.yang:6: warning: imported module "ietf-yang-types" not used`

Possible solution: remove the unused import.

**Comment by PrathibaJee** [comment]
In the current YANG https://github.com/openBackhaul/ltpAugment/blob/tsp/LtpAugment_1.0.0-tsp.200826.0800a+yang.1.zip , the unused module "ietf-yang-types" is removed.

**Comment by openBackhaul** [comment]
Already solved.
